import { Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "@/store/StoreProvider";
import "./globals.css";
import Loader from "@/components/common/Loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen h-screen bg-[#F5F5F5]`}>
        <StoreProvider>
          <Loader />
          <Suspense>{children}</Suspense>
        </StoreProvider>
      </body>
    </html>
  );
}
